code --install-extension beardedbear.beardedtheme
code --install-extension dokca.42-ft-count-line
code --install-extension donjayamanne.githistory
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension golang.go
code --install-extension gruntfuggly.todo-tree
code --install-extension hoovercj.vscode-settings-cycler
code --install-extension keyhr.42-c-format
code --install-extension kube.42header
code --install-extension mariusvanwijk-joppekoers.codam-norminette-3
code --install-extension matepek.vscode-catch2-test-adapter
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.test-adapter-converter
code --install-extension naumovs.color-highlight
code --install-extension pkief.material-icon-theme
code --install-extension ritwickdey.liveserver
code --install-extension svelte.svelte-vscode
code --install-extension tomoki1207.pdf
code --install-extension tomoki1207.selectline-statusbar
code --install-extension tonybaloney.vscode-pets
code --install-extension twxs.cmake
code --install-extension vscodevim.vim
code --install-extension waderyan.gitblame